# Generated by Django 3.1.1 on 2020-09-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default-profile.jpg', upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loudness', models.CharField(default='', max_length=20)),
                ('athleticism', models.CharField(default='', max_length=20)),
                ('musicality', models.CharField(default='', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.profile')),
            ],
        ),
    ]
