# Generated by Django 3.1.1 on 2020-09-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200912_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='users.profile'),
        ),
    ]
