# Generated by Django 3.1.1 on 2020-09-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200912_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='athleticism',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='loudness',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='musicality',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
