# Generated by Django 3.1.1 on 2020-09-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200912_1822'),
        ('users', '0009_message_reply'),
    ]

    operations = [
    ]
