# Generated by Django 3.1.1 on 2020-09-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20200913_0151'),
        ('users', '0010_merge_20200913_0531'),
    ]

    operations = [
    ]
